#!/usr/bin/env python3

import re
import argparse


def convert_vmd_to_ang(input_file, output_file):
    """
    Convert VMD format atomic coordinates to Ang format.
    """
    atom_lines = []

    # Read input file
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Skip header lines if needed
    start_idx = 0
    for i, line in enumerate(lines):
        if re.match(r'^\s*[A-Z]', line):
            start_idx = i
            break

    # Extract atom data
    for line in lines[start_idx:]:
        parts = line.split()
        if len(parts) >= 4 and re.match(r'^[A-Z]', parts[0]):
            atom_type = parts[0]
            x = float(parts[1])
            y = float(parts[2])
            z = float(parts[3])
            atom_lines.append((atom_type, x, y, z))

    # Write output file
    with open(output_file, 'w') as f:
        f.write("# Atomic coordinates\n")
        f.write(f"NumberOfAtoms {len(atom_lines)}\n")
        f.write("AtomicCoordinatesFormat Ang\n")
        f.write("%block AtomicCoordinatesAndAtomicSpecies\n")

        for atom_type, x, y, z in atom_lines:
            f.write(f"{x:.6f} {y:.6f} {z:.6f} 1\n")

        f.write("%endblock AtomicCoordinatesAndAtomicSpecies\n")


def convert_ang_to_vmd(input_file, output_file):
    """
    Convert Ang format atomic coordinates to VMD format.
    """
    atom_lines = []

    # Read input file
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Extract atom data
    reading_block = False
    atom_count = 0
    atoms = []

    for line in lines:
        if "%block AtomicCoordinatesAndAtomicSpecies" in line:
            reading_block = True
            continue
        elif "%endblock" in line:
            reading_block = False
            continue
        elif "NumberOfAtoms" in line:
            parts = line.split()
            atom_count = int(parts[-1])
            continue

        if reading_block:
            parts = line.split()
            if len(parts) >= 4:
                x = float(parts[0])
                y = float(parts[1])
                z = float(parts[2])
                # In this simplified version, we'll assign atom types based on index
                # You might want to use a more sophisticated mapping in a real application
                atom_type = "C"  # Default to Carbon
                atoms.append((atom_type, x, y, z))

    # Write output file - use VMD format
    with open(output_file, 'w') as f:
        f.write(f"{len(atoms)}\n")
        f.write("generated by VMD\n")

        for i, (atom_type, x, y, z) in enumerate(atoms):
            f.write(f"{atom_type} {x:.6f} {y:.6f} {z:.6f}\n")


def main():
    parser = argparse.ArgumentParser(description='Convert between VMD and Ang atomic coordinate formats.')
    parser.add_argument('input_file', help='Input coordinate file')
    parser.add_argument('output_file', help='Output coordinate file')
    parser.add_argument('--direction', choices=['vmd2ang', 'ang2vmd'], required=True,
                        help='Conversion direction (vmd2ang or ang2vmd)')

    args = parser.parse_args()

    if args.direction == 'vmd2ang':
        convert_vmd_to_ang(args.input_file, args.output_file)
        print(f"Converted {args.input_file} from VMD format to Ang format in {args.output_file}")
    else:
        convert_ang_to_vmd(args.input_file, args.output_file)
        print(f"Converted {args.input_file} from Ang format to VMD format in {args.output_file}")


if __name__ == "__main__":
    main()