#!/usr/bin/env python3

import re
import argparse


def convert_vmd_to_ang(input_file, output_file, atom_type_map=None):
    """
    Convert VMD format atomic coordinates to Ang format.

    Parameters:
    - input_file: path to VMD format file
    - output_file: path to output Ang format file
    - atom_type_map: dictionary mapping element symbols to numeric types
    """
    atom_lines = []

    # Default atom type map if none provided
    if atom_type_map is None:
        atom_type_map = {"H": 1, "C": 2, "N": 3, "O": 4, "P": 5, "S": 6}

    # Read input file
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Skip header lines if needed
    start_idx = 0
    for i, line in enumerate(lines):
        if re.match(r'^\s*[A-Z]', line):
            start_idx = i
            break

    # Extract atom data
    for line in lines[start_idx:]:
        parts = line.split()
        if len(parts) >= 4 and re.match(r'^[A-Z]', parts[0]):
            atom_type = parts[0]
            x = float(parts[1])
            y = float(parts[2])
            z = float(parts[3])

            # Get numerical type from map, default to 1 if not found
            type_num = atom_type_map.get(atom_type, 1)
            atom_lines.append((atom_type, x, y, z, type_num))

    # Write output file
    with open(output_file, 'w') as f:
        f.write("# Atomic coordinates\n")
        f.write(f"NumberOfAtoms {len(atom_lines)}\n")
        f.write("AtomicCoordinatesFormat Ang\n")
        f.write("%block AtomicCoordinatesAndAtomicSpecies\n")

        for _, x, y, z, type_num in atom_lines:
            f.write(f"{x:.6f} {y:.6f} {z:.6f} {type_num}\n")

        f.write("%endblock AtomicCoordinatesAndAtomicSpecies\n")


def convert_ang_to_vmd(input_file, output_file, reverse_atom_type_map=None):
    """
    Convert Ang format atomic coordinates to VMD format.

    Parameters:
    - input_file: path to Ang format file
    - output_file: path to output VMD format file
    - reverse_atom_type_map: dictionary mapping numeric types to element symbols
    """
    # Default reverse atom type map if none provided
    if reverse_atom_type_map is None:
        reverse_atom_type_map = {1: "H", 2: "C", 3: "N", 4: "O", 5: "P", 6: "S"}

    # Read input file
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Extract atom data
    reading_block = False
    atom_count = 0
    atoms = []

    for line in lines:
        if "%block AtomicCoordinatesAndAtomicSpecies" in line:
            reading_block = True
            continue
        elif "%endblock" in line:
            reading_block = False
            continue
        elif "NumberOfAtoms" in line:
            parts = line.split()
            atom_count = int(parts[-1])
            continue

        if reading_block:
            parts = line.split()
            if len(parts) >= 4:
                x = float(parts[0])
                y = float(parts[1])
                z = float(parts[2])
                type_num = int(parts[3])

                # Get atom symbol from reverse map, default to "X" if not found
                atom_type = reverse_atom_type_map.get(type_num, "X")
                atoms.append((atom_type, x, y, z))

    # Write output file - use VMD format
    with open(output_file, 'w') as f:
        f.write(f"{len(atoms)}\n")
        f.write("generated by VMD\n")

        for i, (atom_type, x, y, z) in enumerate(atoms):
            f.write(f"{atom_type} {x:.6f} {y:.6f} {z:.6f}\n")


def main():
    parser = argparse.ArgumentParser(description='Convert between VMD and Ang atomic coordinate formats.')
    parser.add_argument('input_file', help='Input coordinate file')
    parser.add_argument('output_file', help='Output coordinate file')
    parser.add_argument('--direction', choices=['vmd2ang', 'ang2vmd'], required=True,
                        help='Conversion direction (vmd2ang or ang2vmd)')
    parser.add_argument('--atom-type-map', type=str, default=None,
                        help='Atom type mapping in format "H:1,C:2,N:3" (for vmd2ang)')
    parser.add_argument('--reverse-atom-type-map', type=str, default=None,
                        help='Reverse atom type mapping in format "1:H,2:C,3:N" (for ang2vmd)')

    args = parser.parse_args()

    # Parse atom type maps if provided
    atom_type_map = None
    if args.atom_type_map:
        atom_type_map = {}
        pairs = args.atom_type_map.split(',')
        for pair in pairs:
            symbol, num = pair.split(':')
            atom_type_map[symbol.strip()] = int(num.strip())

    reverse_atom_type_map = None
    if args.reverse_atom_type_map:
        reverse_atom_type_map = {}
        pairs = args.reverse_atom_type_map.split(',')
        for pair in pairs:
            num, symbol = pair.split(':')
            reverse_atom_type_map[int(num.strip())] = symbol.strip()

    if args.direction == 'vmd2ang':
        convert_vmd_to_ang(args.input_file, args.output_file, atom_type_map)
        print(f"Converted {args.input_file} from VMD format to Ang format in {args.output_file}")
    else:
        convert_ang_to_vmd(args.input_file, args.output_file, reverse_atom_type_map)
        print(f"Converted {args.input_file} from Ang format to VMD format in {args.output_file}")


if __name__ == "__main__":
    main()

#python xyz2fdf1.py DMP-Au.fdf dmp-elec.xyz --direction ang2vmd --reverse-atom-type-map "2:H,3:C,4:N,5:O,1:Au"
#python xyz2fdf1.py dmp-elec-bonds.xyz dmp-w-bonds.fdf --direction vmd2ang --atom-type-map "H:2,C:3,N:4,O:5,Au:1"
